server:
  port: 8761 # 设置 Eureka-Server 的端口

spring:
  application:
    name: eureka-server

#Eureka-Server 会启动一个 Eureka-Client 客户端，用于 Eureka-Server 集群之间的请求交互，
#因为这里我们仅仅搭建 Eureka-Server 单节点，所以设置 register-with-eureka 和 fetch-registry 配置项为 false，无需相互注册。
eureka:
  client:
    register-with-eureka: false # 不注册到 Eureka-Server，默认为 true
    fetch-registry: false # 不从 Eureka-Server 获取注册表，默认为 true