spring:
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        namespace: d2e86223-c1ad-45e8-aab7-454e34a9cb26 # Nacos 命名空间 uat 的编号
