


#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    xa:
#      data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
#    druid:
#      # 连接池的配置信息
#      # 初始化大小，最小，最大
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      # 配置获取连接等待超时的时间
#      maxWait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#spring:
#  data:
#    mongodb:
#      uri: mongodb://127.0.0.1:27018,127.0.0.1:27019/test1?authSource=test1&slaveOk=true&replicaSet=zxqTest&write=1&readPreference=secondaryPreferred&connectTimeoutMS=300000
#server:
#  port: 9090