spring:
  application:
    name: demo-consumer # Spring 应用名
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址

server:
  port: 28080 # 服务器端口。默认为 8080

#通过 feign.httpclient 配置项，我们可以开启 Feign Apache HttpClient，并进行自定义配置。
#在 FeignHttpClientProperties 配置属性类中，还有其它配置项，胖友可以简单看看。
#不过有一点要注意，虽然说 feign.httpclient.enable 默认为 true 开启，但是还是需要引入 feign-httpclient 依赖，才能创建 ApacheHttpClient 对象。

feign:
  # Feign Apache HttpClient 配置项，对应 FeignHttpClientProperties 配置属性类
  httpclient:
    enabled: true # 是否开启。默认为 true
    max-connections: 200 # 最大连接数。默认为 200
    max-connections-per-route: 50 # 每个路由的最大连接数。默认为 50。router = host + port
