spring:
  application:
    name: demo-provider # Spring 应用名

server:
  port: 18080 # 服务器端口。默认为 8080

#  ① 设置 eureka.client.register-with-eureka 为 true，注册当前服务到 Eureka-Server 注册中心中。
#  ② 设置 eureka.client.fetch-registry 为 true，从 Eureka-Server 注册中心拉取注册表。
#  实际上，这里可以设置 false，因为在实例中仅仅扮演服务提供者的角色。
#  ③ eureka.client.service-url 配置项，设置连接的 Eureka-Server 地址。
#  Eureka 是有多 Zone 区域的概念，不过一般用不到，
#  因此这里我们配置 defaultZone 默认区域为 Eureka-Server 地址 http://127.0.0.1:8761/eureka/ 即可，
#  即我们搭建的 Eureka-Server 的地址。


#  按照 http://{账号}:{密码}@{Eureka-Server 地址} 的格式，
#  我们设置 eureka.client.service-url.defaultZone 配置项为 http://eureka:123456@127.0.0.1:8761/eureka/。
eureka:
  client:
    register-with-eureka: true # 注册到 Eureka-Server，默认为 true
    fetch-registry: true # 从 Eureka-Server 获取注册表，默认为 true
    service-url:
      defaultZone: http://eureka:123456@127.0.0.1:8761/eureka/  # Eureka-Server 地址